# Site setings
name: 'NUCLEARKATIE'
description: 'Katie is driven by two of the largest problems facing our world today: climate change and nuclear weapons.'
meta_description: ''
logo: 'assets/images/bitmap.png'
favicon: 'assets/images/atoms.ico'
baseurl:
production_url: http://nuclearkatie.com/
disqus: 'nuclearkatie'
#mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: atomz.gif
# Add your GA Tracking Id
ga_analytics: UA-134095464-1


# Author
author:
  name: 'Katie Mummah'
  image: 'mummah_trinitite.jpg'
  greetings: ''
  description: "My name is Katie Mummah. I'm a nuclear engineer and clean energy advocate. It’s nice to meet you."
  bio: 'Katie is a nuclear engineer and avid Bluesky poster. You can find her on Bluesky at <a href="https://bsky.app/profile/nuclearkatie.com">@nuclearkatie.com</a>'

# Contact form setings
email: katiemummah@gmail.com
contact_page_description: # "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. I'll get back to you as soon as possible!"

# Social links
twitter: 'nuclearkatie'
# facebook: ''
github: 'nuclearkatie'
# codepen: ''
# dribbble: ''
medium: '@nuclearkatie'
# pinterest: ''
linkedin: 'nuclearkatie'
# producthunt: ''

# Navigation
navigation:
  - text: About
    url: /about
  - text: Resume/CV
    url: /cv
  - text: Research
    url: /research
#  - text: Style Guide
#    url: /style-guide/
  - text: Uranium glass
    url: uranium-glass
  - text: Contact Me
    url: /contact
    

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
